name: Java CI/CD with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (JDK 17, for example)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      # Build and test the project with Maven
      - name: Build with Maven
        run: mvn clean install

      # Run tests
      - name: Run tests
        run: mvn test

      # (Optional) Upload artifact to GitHub
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-artifact
          path: target/*.jar
