name: Java CI/CD with Maven

on:
  push:
    branches:
      
- main
pull_request:
  branches:
- main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      
name: Checkout code
      uses: actions/checkout@v3

      # Configurar o Java (JDK 17, por exemplo)
      
name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

      # Rodar o Maven para construir e testar o projeto
      
name: Build with Maven
      run: mvn clean install

      # Rodar os testes do projeto
      
name: Run tests
      run: mvn test

      # (Opcional) Publicar a artefato para o GitHub
      
name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-artifact
        path: target/*.jar
